**Student Name: Huynh Truong Tu**

Below are my assignment for Matrix Scratch problem

----------------------------------------------------------------------

### [Problem 1] Matrix product is calculated manually

**Formula:**

If A is an m × n matrix and B is an n × p matrix,

$$ \mathbf {A} ={\begin{pmatrix}a_{11}&a_{12}&\cdots &a_{1n}\\a_{21}&a_{22}&\cdots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\cdots &a_{mn}\\\end{pmatrix}},
\quad \mathbf {B} ={\begin{pmatrix}b_{11}&b_{12}&\cdots &b_{1p}\\b_{21}&b_{22}&\cdots &b_{2p}\\\vdots &\vdots &\ddots &\vdots \\b_{n1}&b_{n2}&\cdots &b_{np}\\\end{pmatrix}} $$

the matrix product C = AB (denoted without multiplication signs or dots) is defined to be the m × p matrix

$$ {\displaystyle \mathbf {C} ={\begin{pmatrix}c_{11}&c_{12}&\cdots &c_{1p}\\c_{21}&c_{22}&\cdots &c_{2p}\\\vdots &\vdots &\ddots &\vdots \\c_{m1}&c_{m2}&\cdots &c_{mp}\\\end{pmatrix}}}$$

Such that
$$ c_{ij}=a_{i1}b_{1j}+a_{i2}b_{2j}+\cdots +a_{in}b_{nj}=\sum _{k=1}^{n}a_{ik}b_{kj}$$
<center>for i = 1, ..., m and j = 1, ..., p.

> Source: https://en.wikipedia.org/wiki/Matrix_multiplication

Thus, we have:
$$ \mathbf {A} ={\begin{pmatrix}-1&2&3\\4&-5&6\\7&8&9\\\end{pmatrix}},
\quad \mathbf {B} = {\begin{pmatrix}0&2&1\\0&2&-8\\2&9&-1\\\end{pmatrix}} $$

$$ c_{11}=\sum _{k=1}^{3}a_{1k}b_{k1}=(-1)x0+2x0+3x2=6 $$
$$c_{12}=\sum _{k=1}^{3}a_{1k}b_{k2}=29$$
$$c_{13}=\sum _{k=1}^{3}a_{1k}b_{k3}=-20$$
$$c_{21}=\sum _{k=1}^{3}a_{2k}b_{k1}=12$$
$$c_{22}=\sum _{k=1}^{3}a_{2k}b_{k2}=52$$
$$c_{23}=\sum _{k=1}^{3}a_{2k}b_{k3}=38$$
$$c_{31}=\sum _{k=1}^{3}a_{3k}b_{k1}=-18$$
$$c_{32}=\sum _{k=1}^{3}a_{3k}b_{k2}=-51$$
$$c_{33}=\sum _{k=1}^{3}a_{3k}b_{k3}=-48$$



$$ \mathbf {C} ={\begin{pmatrix}6&29&-20\\12&52&38\\-18&-51&-48\\\end{pmatrix}} $$

### [Problem 2] Calculation by NumPy function

In [77]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [78]:
c_ndarray = np.matmul(a_ndarray,b_ndarray)
print(c_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


* Yes, this matches my manual result

### [Problem 3] Implementation of calculation of a certain element

In [80]:
zero_element=0
for _ in range(0,3):
            zero_element += a_ndarray[0,_]*b_ndarray[_,0]
print("The (0,0) element's value is: {}".format(zero_element))

The (0,0) element's value is: 6


### [Problem 4] Creating a function that performs matrix multiplication

In [66]:
def matrix_product(a,b):
    c_ndarray_ver2 = np.zeros((3,3))
    for col in range(0,3):
        for row in range(0,3):
            for _ in range(0,3):
                c_ndarray_ver2[col,row] += a_ndarray[col,_]*b_ndarray[_,row]
    return c_ndarray_ver2
matrix_product(a_ndarray,b_ndarray)

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

### [Problem 5] Judge the input whose calculation is not defined

In [53]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [74]:
def matrix_product(a,b):
    a_num_cols, a_num_rows = a.shape
    b_num_cols, b_num_rows = b.shape
    if a_num_rows == b_num_cols:
        c_ndarray_ver2 = np.zeros((a_num_cols,b_num_rows))
        for col in range(0,a_num_cols):
            for row in range(0,b_num_rows):
                for _ in range(0,b_num_cols):
                    c_ndarray_ver2[col,row] += a[col,_]*b[_,row]
        return c_ndarray_ver2
    else: 
        print('The matrix product is defined') 
        return None
matrix_product(d_ndarray,e_ndarray)

The matrix product is defined


### [Problem 6] Transposition

In [75]:
d_transpose = np.transpose(d_ndarray)
matrix_product(d_transpose, e_ndarray)

array([[ 33., -28.,   9.],
       [-48.,  41.,  -6.],
       [  9.,  -6.,  45.]])

======================================================================================================================

This is the end of my assignment, thank you for reading!