# Problem 1 - Sharing and executing the official tutorial model

### NOTE
Here we have tensorflow quick start from [Link](https://www.tensorflow.org/tutorials/quickstart/beginner)

In [1]:
import tensorflow as tf

## Data

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

## Model

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

## Untrained Model

### Logits

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.42534143,  0.33701155, -0.03589313,  0.48529944,  0.09422559,
        -0.60956156, -0.3407547 , -0.60975283,  0.3503093 ,  0.42352787]],
      dtype=float32)

### Probability
through softmax

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.06231572, 0.13356212, 0.09198836, 0.1549116 , 0.10477139,
        0.05183127, 0.06781616, 0.05182135, 0.13535006, 0.14563201]],
      dtype=float32)

## Loss

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

## Compile and Fit

In [7]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [8]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 957us/step - loss: 0.2893 - accuracy: 0.9161
Epoch 2/5
1875/1875 [==============================] - 2s 971us/step - loss: 0.1420 - accuracy: 0.9581
Epoch 3/5
1875/1875 [==============================] - 2s 964us/step - loss: 0.1057 - accuracy: 0.9681
Epoch 4/5
1875/1875 [==============================] - 2s 954us/step - loss: 0.0882 - accuracy: 0.9727
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0755 - accuracy: 0.9760


## Evaluation

In [9]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0741 - accuracy: 0.9777 - 287ms/epoch - 918us/step


[0.07408832758665085, 0.9776999950408936]

## Another model for usage with probability output

In [10]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [11]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.4097856e-07, 7.3218165e-09, 4.2046204e-06, 1.8473092e-05,
        1.1631680e-11, 2.1615466e-07, 6.2342296e-14, 9.9995732e-01,
        1.5085351e-07, 1.8938765e-05],
       [2.1118700e-09, 1.1185353e-04, 9.9978131e-01, 1.1863421e-05,
        8.3961074e-15, 9.1936017e-05, 3.1781934e-07, 7.8204598e-13,
        2.7778137e-06, 2.4258388e-12],
       [1.2637884e-07, 9.9838758e-01, 2.7642443e-04, 2.3654196e-05,
        2.1186263e-05, 8.9005243e-06, 2.6532303e-05, 9.3138881e-04,
        3.2240391e-04, 1.7862404e-06],
       [9.9992454e-01, 3.3123746e-07, 1.7141459e-05, 4.5199595e-09,
        2.2498480e-07, 1.0129338e-07, 5.1795465e-05, 1.7800351e-06,
        9.5661129e-08, 3.9665892e-06],
       [1.2767096e-06, 1.0392085e-08, 1.4531118e-06, 1.0216092e-08,
        9.9310571e-01, 8.2268116e-08, 2.9685054e-07, 1.3416512e-04,
        8.3253070e-07, 6.7561264e-03]], dtype=float32)>

# This is the end of problem 1 - tensorflow tutorial